// Generated by Wrangler by running `wrangler types`

interface Env {
	KV_CACHE: KVNamespace;
	JWT_SECRET: string;
	JWT_EXPIRES_IN: string;
	NODE_ENV: string;
	LOG_LEVEL: string;
	DB: D1Database;
	ASSETS: Fetcher;
}
